const bkdetails={
  book:[{'title': 'Pride and Prejudice and Zombies Pride and Prejudice and Zombies 1'},
  {'title': 'Blue Bloods Blue Bloods 1'},
  {'title': 'Me Before You Me Before You 1'},
  {'title': 'Sharp Objects'},
  {'title': 'The Way of Kings The Stormlight Archive 1'},
  {'title': 'The Andromeda Strain'},
  {'title': 'A Dance with Dragons A Song of Ice and Fire 5'},
  {'title': 'A Clash of Kings A Song of Ice and Fire 2'},
  {'title': 'The Eye of the World Wheel of Time 1'},
  {'title': 'The Great Hunt Wheel of Time 2'},
  {'title': 'Eleven Minutes'},
  {'title': 'The Ultimate Hitchhikers Guide to the Galaxy'},
  {'title': 'Hamlet Screenplay Introduction And Film Diary'},
  {'title': 'From Dead to Worse Sookie Stackhouse 8'},
  {'title': 'Dead as a Doornail Sookie Stackhouse 5'},
  {'title': 'Living Dead in Dallas Sookie Stackhouse 2'},
  {'title': 'The Girl Who Loved Tom Gordon'},
  {'title': 'Doctor Sleep'},
  {'title': 'Harry Potter Boxset Harry Potter 17'},
  {'title': 'Harry Potter and the Cursed Child Parts One and Two Harry Potter 8'},
  {'title': 'I Am the Messenger'},
  {'title': 'I Robot Robot 01'},
  {'title': 'The Name of the Wind The Kingkiller Chronicle 1'},
  {'title': 'The Son of Neptune The Heroes of Olympus 2'},
  {'title': 'Anna and the French Kiss Anna and the French Kiss 1'},
  {'title': 'The Short Second Life of Bree Tanner Twilight 35'},
  {'title': 'Midnight Sun Twilight 15'},
  {'title': 'Fallen Too Far Rosemary Beach 1 Too Far 1'},
  {'title': 'The TellTale Heart and Other Writings'},
  {'title': 'A Wizard of Earthsea Earthsea Cycle 1'},
  {'title': 'The Devil Wears Prada The Devil Wears Prada 1'},
  {'title': 'Freakonomics A Rogue Economist Explores the Hidden Side of Everything Freakonomics 1'},
  {'title': 'Angelfall Penryn the End of Days 1'},
  {'title': 'Bridget Joness Diary Bridget Jones 1'},
  {'title': 'Watership Down Watership Down 1'},
  {'title': 'The Firm Penguin Readers Level 5'},
  {'title': 'Good Omens The Nice and Accurate Prophecies of Agnes Nutter Witch'},
  {'title': 'Where the Sidewalk Ends'},
  {'title': 'The Very Hungry Caterpillar'},
  {'title': 'We Should All Be Feminists'},
  {'title': 'The Five People You Meet in Heaven'},
  {'title': 'Mort Death 1 Discworld 4'},
  {'title': 'The Color of Magic Discworld 1 Rincewind 1'},
  {'title': 'Betrayed House of Night 2'},
  {'title': 'Poison Study Study 1'},
  {'title': 'Lover Mine Black Dagger Brotherhood 8'},
  {'title': 'Eldest The Inheritance Cycle 2'},
  {'title': 'Brisingr The Inheritance Cycle 3'},
  {'title': 'Eragon The Inheritance Cycle 1'},
  {'title': 'Pretty Little Liars Pretty Little Liars 1'},
  {'title': 'The Chronicles of Narnia Chronicles of Narnia 17'},
  {'title': 'The Paris Wife'},
  {'title': 'I Am Malala The Story of the Girl Who Stood Up for Education and Was Shot by the Taliban'},
  {'title': 'Clockwork Princess The Infernal Devices 3'},
  {'title': 'Mrs Frisby and the Rats of NIMH Rats of NIMH 1'},
  {'title': 'Free Four Tobias Tells the Divergent KnifeThrowing Scene Divergent 15'},
  {'title': 'Wonder Wonder 1'},
  {'title': 'Finale Hush Hush 4'},
  {'title': 'The Hunt for Red October Jack Ryan Universe 4'},
  {'title': 'Saga Vol 1 Saga 1'},
  {'title': 'Saga Vol 2 Saga 2'},
  {'title': 'Saga Vol 3 Saga 3'},
  {'title': 'The Namesake'},
  {'title': 'Not That Kind of Girl A Young Woman Tells You What Shes Learned'},
  {'title': 'The Walking Dead Vol 01 Days Gone Bye'},
  {'title': 'Something Borrowed Darcy Rachel 1'},
  {'title': 'Frostbite Vampire Academy 2'},
  {'title': 'This Lullaby'},
  {'title': 'Forever The Wolves of Mercy Falls 3'},
  {'title': 'Catch22 Catch22 1'},
  {'title': 'WinniethePooh WinniethePooh 1'},
  {'title': 'The Coincidence of Callie Kayden The Coincidence 1'},
  {'title': 'Faefever Fever 3'},
  {'title': 'Wicked Lovely Wicked Lovely 1'},
  {'title': 'The Amber Spyglass His Dark Materials 3'},
  {'title': 'Watchmen'},
  {'title': 'Slammed Slammed 1'},
  {'title': 'Confess'},
  {'title': 'The Summer I Turned Pretty Summer 1'},
  {'title': 'Lean In Women Work and the Will to Lead'},
  {'title': 'Shutter Island'},
  {'title': 'Unravel Me Shatter Me 2'},
  {'title': 'Angus Thongs and FullFrontal Snogging Confessions of Georgia Nicolson 1'},
  {'title': 'The Secret The Secret 1'},
  {'title': 'Beastly Beastly 1 Kendra Chronicles 1'},
  {'title': 'Marley and Me Life and Love With the Worlds Worst Dog'},
  {'title': 'The Polar Express'},
  {'title': 'A Child Called It Dave Pelzer 1'},
  {'title': 'Oedipus Rex The Theban Plays 1'},
  {'title': 'The Nanny Diaries Nanny 1'},
  {'title': 'Maus I A Survivors Tale My Father Bleeds History Maus 1'},
  {'title': 'How to Be a Woman'},
  {'title': 'Persepolis The Story of a Childhood Persepolis 1'},
  {'title': 'The City of Ember Book of Ember 1'},
  {'title': 'Wicked The Life and Times of the Wicked Witch of the West The Wicked Years 1'},
  {'title': 'Harry Potter and the Cursed Child Parts 1 2 Harry Potter 8'}]
};
export default bkdetails;